// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

#nullable disable

namespace EFCoreMovie1_RazorPages.Models
{
    public partial class Studio
    {
        public Studio()
        {
            Movies = new HashSet<Movie>();
        }

        public int Id { get; set; }
        public string Name { get; set; }
        public string Hqcity { get; set; }
        public int NoOfEmployees { get; set; }

        public virtual ICollection<Movie> Movies { get; set; }
    }
}